/*
 * Git
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// ItemContent :
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct ItemContent {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<ContentType>,
}

impl ItemContent {
    ///
    pub fn new() -> ItemContent {
        ItemContent {
            content: None,
            content_type: None,
        }
    }

    pub fn builder() -> ItemContentBuilder {
        ItemContentBuilder::create_empty()
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentType {
    #[serde(rename = "rawText")]
    RawText,
    #[serde(rename = "base64Encoded")]
    Base64Encoded,
}

impl Default for ContentType {
    fn default() -> ContentType {
        Self::RawText
    }
}
