/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssistantObjectToolsInner {
    AssistantToolsCode(Box<models::AssistantToolsCode>),
    AssistantToolsFileSearch(Box<models::AssistantToolsFileSearch>),
    AssistantToolsFunction(Box<models::AssistantToolsFunction>),
}

impl Default for AssistantObjectToolsInner {
    fn default() -> Self {
        Self::AssistantToolsCode(Default::default())
    }
}
/// The type of tool being defined: `code_interpreter`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "code_interpreter")]
    CodeInterpreter,
    #[serde(rename = "file_search")]
    FileSearch,
    #[serde(rename = "function")]
    Function,
}

impl Default for Type {
    fn default() -> Type {
        Self::CodeInterpreter
    }
}
