/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// ChatCompletionMessageToolCallFunction : The function that the model called.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct ChatCompletionMessageToolCallFunction {
    /// The name of the function to call.
    #[serde(rename = "name")]
    pub name: String,
    /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    #[serde(rename = "arguments")]
    pub arguments: String,
}

impl ChatCompletionMessageToolCallFunction {
    /// The function that the model called.
    pub fn new(name: String, arguments: String) -> ChatCompletionMessageToolCallFunction {
        ChatCompletionMessageToolCallFunction { name, arguments }
    }

    pub fn builder() -> ChatCompletionMessageToolCallFunctionBuilder {
        ChatCompletionMessageToolCallFunctionBuilder::create_empty()
    }
}
