/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct ChatCompletionNamedToolChoiceFunction {
    /// The name of the function to call.
    #[serde(rename = "name")]
    pub name: String,
}

impl ChatCompletionNamedToolChoiceFunction {
    pub fn new(name: String) -> ChatCompletionNamedToolChoiceFunction {
        ChatCompletionNamedToolChoiceFunction { name }
    }

    pub fn builder() -> ChatCompletionNamedToolChoiceFunctionBuilder {
        ChatCompletionNamedToolChoiceFunctionBuilder::create_empty()
    }
}
