/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// ChatCompletionNamedToolChoice : Specifies a tool the model should use. Use to force the model to call a specific function.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct ChatCompletionNamedToolChoice {
    /// The type of the tool. Currently, only `function` is supported.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "function")]
    pub function: Box<models::ChatCompletionNamedToolChoiceFunction>,
}

impl ChatCompletionNamedToolChoice {
    /// Specifies a tool the model should use. Use to force the model to call a specific function.
    pub fn new(
        r#type: Type, function: models::ChatCompletionNamedToolChoiceFunction,
    ) -> ChatCompletionNamedToolChoice {
        ChatCompletionNamedToolChoice {
            r#type,
            function: Box::new(function),
        }
    }

    pub fn builder() -> ChatCompletionNamedToolChoiceBuilder {
        ChatCompletionNamedToolChoiceBuilder::create_empty()
    }
}
/// The type of the tool. Currently, only `function` is supported.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "function")]
    Function,
}

impl Default for Type {
    fn default() -> Type {
        Self::Function
    }
}
