/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct CompleteUploadRequest {
    /// The ordered list of Part IDs.
    #[serde(rename = "part_ids")]
    pub part_ids: Vec<String>,
    /// The optional md5 checksum for the file contents to verify if the bytes uploaded matches what you expect.
    #[serde(rename = "md5", skip_serializing_if = "Option::is_none")]
    pub md5: Option<String>,
}

impl CompleteUploadRequest {
    pub fn new(part_ids: Vec<String>) -> CompleteUploadRequest {
        CompleteUploadRequest {
            part_ids,
            md5: None,
        }
    }

    pub fn builder() -> CompleteUploadRequestBuilder {
        CompleteUploadRequestBuilder::create_empty()
    }
}
