/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// CreateImageRequestApiModel : The model to use for image generation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct CreateImageRequestApiModel {}

impl CreateImageRequestApiModel {
    /// The model to use for image generation.
    pub fn new() -> CreateImageRequestApiModel {
        CreateImageRequestApiModel {}
    }

    pub fn builder() -> CreateImageRequestApiModelBuilder {
        CreateImageRequestApiModelBuilder::create_empty()
    }
}
