/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// CreateThreadAndRunRequestModel : The ID of the [Model](/docs/api-reference/models) to be used to execute this run. If a value is provided here, it will override the model associated with the assistant. If not, the model associated with the assistant will be used.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct CreateThreadAndRunRequestModel {}

impl CreateThreadAndRunRequestModel {
    /// The ID of the [Model](/docs/api-reference/models) to be used to execute this run. If a value is provided here, it will override the model associated with the assistant. If not, the model associated with the assistant will be used.
    pub fn new() -> CreateThreadAndRunRequestModel {
        CreateThreadAndRunRequestModel {}
    }

    pub fn builder() -> CreateThreadAndRunRequestModelBuilder {
        CreateThreadAndRunRequestModelBuilder::create_empty()
    }
}
