/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// CreateImageEditRequestModel : The model to use for image generation. Only `dall-e-2` is supported at this time.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct CreateImageEditRequestModel {}

impl CreateImageEditRequestModel {
    /// The model to use for image generation. Only `dall-e-2` is supported at this time.
    pub fn new() -> CreateImageEditRequestModel {
        CreateImageEditRequestModel {}
    }

    pub fn builder() -> CreateImageEditRequestModelBuilder {
        CreateImageEditRequestModelBuilder::create_empty()
    }
}
