/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// CreateChatCompletionRequestApiModel : ID of the model to use. See the [model endpoint compatibility](/docs/models/model-endpoint-compatibility) table for details on which models work with the Chat API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct CreateChatCompletionRequestApiModel {}

impl CreateChatCompletionRequestApiModel {
    /// ID of the model to use. See the [model endpoint compatibility](/docs/models/model-endpoint-compatibility) table for details on which models work with the Chat API.
    pub fn new() -> CreateChatCompletionRequestApiModel {
        CreateChatCompletionRequestApiModel {}
    }

    pub fn builder() -> CreateChatCompletionRequestApiModelBuilder {
        CreateChatCompletionRequestApiModelBuilder::create_empty()
    }
}
