/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// CreateSpeechRequestModel : One of the available [TTS models](/docs/models/tts): `tts-1` or `tts-1-hd`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct CreateSpeechRequestModel {}

impl CreateSpeechRequestModel {
    /// One of the available [TTS models](/docs/models/tts): `tts-1` or `tts-1-hd`
    pub fn new() -> CreateSpeechRequestModel {
        CreateSpeechRequestModel {}
    }

    pub fn builder() -> CreateSpeechRequestModelBuilder {
        CreateSpeechRequestModelBuilder::create_empty()
    }
}
