/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// CreateTranscriptionRequestModel : ID of the model to use. Only `whisper-1` (which is powered by our open source Whisper V2 model) is currently available.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct CreateTranscriptionRequestModel {}

impl CreateTranscriptionRequestModel {
    /// ID of the model to use. Only `whisper-1` (which is powered by our open source Whisper V2 model) is currently available.
    pub fn new() -> CreateTranscriptionRequestModel {
        CreateTranscriptionRequestModel {}
    }

    pub fn builder() -> CreateTranscriptionRequestModelBuilder {
        CreateTranscriptionRequestModelBuilder::create_empty()
    }
}
