/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct DeleteVectorStoreResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "deleted")]
    pub deleted: bool,
    #[serde(rename = "object")]
    pub object: Object,
}

impl DeleteVectorStoreResponse {
    pub fn new(id: String, deleted: bool, object: Object) -> DeleteVectorStoreResponse {
        DeleteVectorStoreResponse {
            id,
            deleted,
            object,
        }
    }

    pub fn builder() -> DeleteVectorStoreResponseBuilder {
        DeleteVectorStoreResponseBuilder::create_empty()
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "vector_store.deleted")]
    VectorStorePeriodDeleted,
}

impl Default for Object {
    fn default() -> Object {
        Self::VectorStorePeriodDeleted
    }
}
