/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// FineTuningJobHyperparameters : The hyperparameters used for the fine-tuning job. See the [fine-tuning guide](/docs/guides/fine-tuning) for more details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct FineTuningJobHyperparameters {
    #[serde(rename = "n_epochs")]
    pub n_epochs: Box<models::FineTuningJobHyperparametersNEpochs>,
}

impl FineTuningJobHyperparameters {
    /// The hyperparameters used for the fine-tuning job. See the [fine-tuning guide](/docs/guides/fine-tuning) for more details.
    pub fn new(
        n_epochs: models::FineTuningJobHyperparametersNEpochs,
    ) -> FineTuningJobHyperparameters {
        FineTuningJobHyperparameters {
            n_epochs: Box::new(n_epochs),
        }
    }

    pub fn builder() -> FineTuningJobHyperparametersBuilder {
        FineTuningJobHyperparametersBuilder::create_empty()
    }
}
