/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// FineTuningJobError : For fine-tuning jobs that have `failed`, this will contain more information on the cause of the failure.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct FineTuningJobError {
    /// A machine-readable error code.
    #[serde(rename = "code")]
    pub code: String,
    /// A human-readable error message.
    #[serde(rename = "message")]
    pub message: String,
    /// The parameter that was invalid, usually `training_file` or `validation_file`. This field will be null if the failure was not parameter-specific.
    #[serde(rename = "param", deserialize_with = "Option::deserialize")]
    pub param: Option<String>,
}

impl FineTuningJobError {
    /// For fine-tuning jobs that have `failed`, this will contain more information on the cause of the failure.
    pub fn new(code: String, message: String, param: Option<String>) -> FineTuningJobError {
        FineTuningJobError {
            code,
            message,
            param,
        }
    }

    pub fn builder() -> FineTuningJobErrorBuilder {
        FineTuningJobErrorBuilder::create_empty()
    }
}
