/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// Image : Represents the url or the content of an image generated by the OpenAI API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct Image {
    /// The base64-encoded JSON of the generated image, if `response_format` is `b64_json`.
    #[serde(rename = "b64_json", skip_serializing_if = "Option::is_none")]
    pub b64_json: Option<String>,
    /// The URL of the generated image, if `response_format` is `url` (default).
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The prompt that was used to generate the image, if there was any revision to the prompt.
    #[serde(rename = "revised_prompt", skip_serializing_if = "Option::is_none")]
    pub revised_prompt: Option<String>,
}

impl Image {
    /// Represents the url or the content of an image generated by the OpenAI API.
    pub fn new() -> Image {
        Image {
            b64_json: None,
            url: None,
            revised_prompt: None,
        }
    }

    pub fn builder() -> ImageBuilder {
        ImageBuilder::create_empty()
    }
}
