/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct MessageContentTextAnnotationsFileCitationObjectFileCitation {
    /// The ID of the specific File the citation is from.
    #[serde(rename = "file_id")]
    pub file_id: String,
}

impl MessageContentTextAnnotationsFileCitationObjectFileCitation {
    pub fn new(file_id: String) -> MessageContentTextAnnotationsFileCitationObjectFileCitation {
        MessageContentTextAnnotationsFileCitationObjectFileCitation { file_id }
    }

    pub fn builder() -> MessageContentTextAnnotationsFileCitationObjectFileCitationBuilder {
        MessageContentTextAnnotationsFileCitationObjectFileCitationBuilder::create_empty()
    }
}
