/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContentTextObjectTextAnnotationsInner {
    MessageContentTextAnnotationsFileCitationObject(
        Box<models::MessageContentTextAnnotationsFileCitationObject>,
    ),
    MessageContentTextAnnotationsFilePathObject(
        Box<models::MessageContentTextAnnotationsFilePathObject>,
    ),
}

impl Default for MessageContentTextObjectTextAnnotationsInner {
    fn default() -> Self {
        Self::MessageContentTextAnnotationsFileCitationObject(Default::default())
    }
}
/// Always `file_citation`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file_citation")]
    Citation,
    #[serde(rename = "file_path")]
    Path,
}

impl Default for Type {
    fn default() -> Type {
        Self::Citation
    }
}
