/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct MessageContentTextObjectText {
    /// The data that makes up the text.
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "annotations")]
    pub annotations: Vec<models::MessageContentTextObjectTextAnnotationsInner>,
}

impl MessageContentTextObjectText {
    pub fn new(
        value: String, annotations: Vec<models::MessageContentTextObjectTextAnnotationsInner>,
    ) -> MessageContentTextObjectText {
        MessageContentTextObjectText { value, annotations }
    }

    pub fn builder() -> MessageContentTextObjectTextBuilder {
        MessageContentTextObjectTextBuilder::create_empty()
    }
}
