/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct ModifyAssistantRequestToolResourcesFileSearch {
    /// Overrides the [vector store](/docs/api-reference/vector-stores/object) attached to this assistant. There can be a maximum of 1 vector store attached to the assistant.
    #[serde(rename = "vector_store_ids", skip_serializing_if = "Option::is_none")]
    pub vector_store_ids: Option<Vec<String>>,
}

impl ModifyAssistantRequestToolResourcesFileSearch {
    pub fn new() -> ModifyAssistantRequestToolResourcesFileSearch {
        ModifyAssistantRequestToolResourcesFileSearch {
            vector_store_ids: None,
        }
    }

    pub fn builder() -> ModifyAssistantRequestToolResourcesFileSearchBuilder {
        ModifyAssistantRequestToolResourcesFileSearchBuilder::create_empty()
    }
}
