/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// RunObjectRequiredAction : Details on the action required to continue the run. Will be `null` if no action is required.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct RunObjectRequiredAction {
    /// For now, this is always `submit_tool_outputs`.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "submit_tool_outputs")]
    pub submit_tool_outputs: Box<models::RunObjectRequiredActionSubmitToolOutputs>,
}

impl RunObjectRequiredAction {
    /// Details on the action required to continue the run. Will be `null` if no action is required.
    pub fn new(
        r#type: Type, submit_tool_outputs: models::RunObjectRequiredActionSubmitToolOutputs,
    ) -> RunObjectRequiredAction {
        RunObjectRequiredAction {
            r#type,
            submit_tool_outputs: Box::new(submit_tool_outputs),
        }
    }

    pub fn builder() -> RunObjectRequiredActionBuilder {
        RunObjectRequiredActionBuilder::create_empty()
    }
}
/// For now, this is always `submit_tool_outputs`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "submit_tool_outputs")]
    SubmitToolOutputs,
}

impl Default for Type {
    fn default() -> Type {
        Self::SubmitToolOutputs
    }
}
