/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct RunStepDetailsToolCallsCodeOutputImageObjectImage {
    /// The [file](/docs/api-reference/files) ID of the image.
    #[serde(rename = "file_id")]
    pub file_id: String,
}

impl RunStepDetailsToolCallsCodeOutputImageObjectImage {
    pub fn new(file_id: String) -> RunStepDetailsToolCallsCodeOutputImageObjectImage {
        RunStepDetailsToolCallsCodeOutputImageObjectImage { file_id }
    }

    pub fn builder() -> RunStepDetailsToolCallsCodeOutputImageObjectImageBuilder {
        RunStepDetailsToolCallsCodeOutputImageObjectImageBuilder::create_empty()
    }
}
