# Code Formatting Style
use_small_heuristics = "Default"
max_width = 100                   # Maximum line width for better readability
hard_tabs = false                 # Use spaces for indentation
tab_spaces = 4                    # Number of spaces per tab
newline_style = "unix"            # Unix-style newlines, lowercased to fit convention

# Import Ordering
reorder_imports = true            # Reorder imports automatically

# Control Structures
brace_style = "SameLineWhere"     # Braces start on the same line for control structures

# Function Arguments and Calls
fn_params_layout = "Compressed"   # Use compressed layout for function arguments
fn_call_width = 80                # Width threshold for collapsing function call args

# Field and Try Shorthand
use_field_init_shorthand = true   # Use shorthand for struct field initialization
use_try_shorthand = true          # Use shorthand for try operator

# Item & Module Formatting
item_brace_style = "PreferSameLine" # Prefer braces on the same line for structs, enums, etc.

# Whitespace Control
space_before_colon = false        # Do not put space before colons
space_after_colon = true          # Put space after colons
spaces_around_ranges = false      # No spaces around range operators

# Comment Handling
wrap_comments = false             # Disabled as it requires nightly
comment_width = 80                # Adjusted to a standard width

# Error Handling
error_on_line_overflow = false    # Disabled as it requires nightly
error_on_unformatted = false      # Disabled as it requires nightly
