# Code Formatting Style
use_small_heuristics = "Default"
max_width = 100                   # Maximum line width for better readability
hard_tabs = false                 # Use spaces for indentation
tab_spaces = 4                    # Number of spaces per tab
newline_style = "unix"            # Unix-style newlines, lowercased to fit convention

# Import Ordering
reorder_imports = true            # Reorder imports automatically

# Control Structures
# brace_style = "SameLineWhere"   # Removed due to nightly requirement

# Function Arguments and Calls
fn_params_layout = "Compressed"   # Use compressed layout for function arguments
fn_call_width = 80                # Width threshold for collapsing function call args

# Field and Try Shorthand
use_field_init_shorthand = true   # Use shorthand for struct field initialization
use_try_shorthand = true          # Use shorthand for try operator

# Item & Module Formatting
# item_brace_style = "PreferSameLine" # Removed due to nightly requirement

# Whitespace Control
# space_before_colon = false       # Removed due to nightly requirement
# space_after_colon = true         # Removed due to nightly requirement
# spaces_around_ranges = false     # Removed due to nightly requirement

# Comment Handling
# wrap_comments = false            # Removed due to nightly requirement
# comment_width = 80               # Removed due to nightly requirement

# Error Handling
# error_on_line_overflow = false   # Removed due to nightly requirement
# error_on_unformatted = false     # Removed due to nightly requirement
