[workspace]
members = [
    "core",
    "api", "tests",
]

exclude = [
    "integrations/github"
]

resolver = "2"

[workspace.dependencies]
devpulse_core = { path = "core" }
devpulse = { path = "api" }