[package]
name = "rustrict"
edition = "2021"
version.workspace = true

[[bin]]
name = "rustrict"
path = "src/bin/main.rs"

[features]
default = []
server = []

[dependencies]
petgraph = "0.6.5"
prost = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pest = "2.1"
pest_derive = "2.1"
tonic = "0.12.1"
thiserror = "1.0.63"
rand = "0.8.5"
tokio = "1.39.2"
derive_more = { version = "1.0.0-beta.7", features = ["full"] }
tracing = "0.1.40"
skiplist = "0.5.1"
snafu = "0.8.1"
serde_yaml = "0.9.34+deprecated"
color-eyre = "0.6.1"
anyhow = "1.0.86"
tracing-error = "0.2.0"

[build-dependencies]
tonic-build = "0.12.1"