# .azure/azure-pipelines.yml
trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: self

variables:
  RUST_VERSION: 'stable'

steps:
  - template: .azure/rust-setup.yaml@self
    parameters:
      rust: $(RUST_VERSION)

  - script: |
      cargo run --bin annotate
    displayName: 'Run Annotation Tests'
