trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: self

variables:
  RUST_VERSION: 'stable'

steps:
  # run tests/create_azure_test_files.sh
  - script: |
      ./tests/create_azure_test_files.sh
    displayName: 'Create Azure Test Files'
  # Include the sub-template for logging commands and annotations
  - template: logging-commands.yml
  - template: rust-setup.yml@self
    parameters:
      rust: $(RUST_VERSION)

  # Cache Cargo dependencies and target directory
  - task: Cache@2
    inputs:
      key: 'cargo | $(Agent.OS) | cargo.lock | $(Build.SourceBranchName)'
      path: |
        ~/.cargo/registry
        ~/.cargo/git
        target
      restoreKeys: |
        cargo | $(Agent.OS) | cargo.lock
        cargo | $(Agent.OS)
    continueOnError: true

  # Restore Cargo environment
  - script: |
      rustup default $RUST_VERSION
      rustup update $RUST_VERSION
    displayName: 'Restore Cargo environment'

  - script: |
      cargo run --bin test_annotations
    env:
      CI_PLATFORM: 'azure'
    displayName: 'Run Annotation Tests'


  - template: .azure-pipelines/templates/rust-test-template.yml
    parameters:
      rustVersion: '1.62.0'