trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CARGO_CACHE_DIR: $(Pipeline.Workspace)/.cargo

jobs:
  - job: Build
    displayName: 'Build and Test'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true

      - task: UseRust@0
        inputs:
          rustVersion: 'stable'

      - script: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config
        displayName: 'Install dependencies'

      - task: Cache@2
        inputs:
          key: 'cargo | "$(Agent.OS)" | cargo.lock'
          path: $(CARGO_CACHE_DIR)
          restoreKeys: |
            cargo | "$(Agent.OS)"
        displayName: 'Cache Cargo dependencies'

      - script: |
          cargo build --verbose
        displayName: 'Build the project'

      - script: |
          cargo test --verbose
        displayName: 'Run tests'

      - script: |
          cargo run --bin annotate
        displayName: 'Run annotation tests'
