trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: self

variables:
  RUST_VERSION: 'stable'

steps:
  - template: rust-setup.yml@self
    parameters:
      rust: $(RUST_VERSION)

  # Cache Cargo dependencies and target directory
  - task: Cache@2
    inputs:
      key: 'cargo | $(Agent.OS) | cargo.lock | $(Build.SourceBranchName)'
      path: |
        ~/.cargo/registry
        ~/.cargo/git
        target
      restoreKeys: |
        cargo | $(Agent.OS) | cargo.lock
        cargo | $(Agent.OS)
    continueOnError: true

  # Restore Cargo environment
  - script: |
      rustup default $RUST_VERSION
      rustup update $RUST_VERSION
    displayName: 'Restore Cargo environment'

  # Verify Annotations: Issue a log item for annotation test
  - script: |
      echo '##vso[task.logissue type=error;sourcepath=.azure/azure-pipelines.yml;linenumber=39;columnnumber=1;]This is a dummy annotation'
    displayName: 'Issue Test Annotation Log Item'

  - script: |
      cargo run --bin annotate
    env:
      CI_PLATFORM: 'azure'
    displayName: 'Run Annotation Tests'
