apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: authentication
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: localhost:5000/authentication
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: authentication-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-postgres
  template:
    metadata:
      labels:
        app: authentication-postgres
    spec:
      containers:
        - name: authentication-postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: authentication
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: changeme
---
