/*
 * OpenAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::configuration;
pub use super::Error;
use crate::{apis::ResponseContent, models};
use cached::proc_macro::cached;
use cached::Cached;
use cached::SizedCache;
use derive_builder::Builder;
use reqwest;
use serde::{Deserialize, Serialize};
use tracing::{debug, error, info, trace, warn};

#[macro_export]
macro_rules! generate_chat_api_client_methods {
    () => {
        /// create_chat_completion method
        pub async fn create_chat_completion(
            &self, params: CreateChatCompletionParams,
        ) -> Result<models::CreateChatCompletionResponse, Error<CreateChatCompletionError>> {
            let result =
                crate::apis::chat_api::create_chat_completion(&self.config, params).await?;
            Ok(result)
        }
    };
}

#[macro_export]
macro_rules! generate_chat_api_client {
    () => {
        use cached::SizedCache;
        use reqwest::Client;
        use std::sync::Arc;

        pub struct ChatApi<'a> {
            config: &'a Arc<configuration::Configuration>,
            client: Client,
        }

        impl<'a> ChatApi<'a> {
            pub fn new(config: &'a Arc<configuration::Configuration>) -> Self {
                ChatApi {
                    config,
                    client: Client::new(),
                }
            }
            /// create_chat_completion method
            pub async fn createchatcompletion(
                &self, params: CreateChatCompletionParams,
            ) -> Result<models::CreateChatCompletionResponse, Error<CreateChatCompletionError>>
            {
                let result =
                    crate::apis::chat_api::create_chat_completion(&self.config, params).await?;
                Ok(result)
            }
        }
    };
}

/// struct for passing parameters to the method [`create_chat_completion`]
#[derive(Clone, Debug, Builder, Default, Serialize, PartialEq)]
#[builder(setter(strip_option, into), default)]
pub struct CreateChatCompletionParams {
    pub create_chat_completion_request: models::CreateChatCompletionRequest,
}

impl CreateChatCompletionParams {
    pub fn builder() -> CreateChatCompletionParamsBuilder {
        CreateChatCompletionParamsBuilder::default()
    }
}

/// struct for typed errors of method [`create_chat_completion`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateChatCompletionError {
    UnknownValue(serde_json::Value),
}

#[tracing::instrument]
pub async fn create_chat_completion(
    configuration: &configuration::Configuration, params: CreateChatCompletionParams,
) -> Result<models::CreateChatCompletionResponse, Error<CreateChatCompletionError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let create_chat_completion_request = params.create_chat_completion_request;

    debug!("Calling create_chat_completion...");

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/chat/completions", local_var_configuration.base_path);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&create_chat_completion_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<CreateChatCompletionError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}
