[package]
name = "devpulse_core"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
url = "2.5.2"
serde_json = { version = "1.0.120", features = ["preserve_order"] }
serde = { version = "1.0.204", features = ["derive"] }
