#[derive(Debug, Clone, Copy)]
enum GitHubEmoji {
    Art,
    Zap,
    Fire,
    Bug,
    Ambulance,
    Sparkles,
    Memo,
    Rocket,
    Lipstick,
    Tada,
    WhiteCheckMark,
    Lock,
    ClosedLockWithKey,
    Bookmark,
    RotatingLight,
    Construction,
    GreenHeart,
    ArrowDown,
    ArrowUp,
    Pushpin,
    ConstructionWorker,
    ChartWithUpwardsTrend,
    Recycle,
    HeavyPlusSign,
    HeavyMinusSign,
    Wrench,
    Hammer,
    GlobeWithMeridians,
    Pencil2,
    Poop,
    Rewind,
    TwistedRightwardsArrows,
    Package,
    Alien,
    Truck,
    PageFacingUp,
    Boom,
    Bento,
    Wheelchair,
    Bulb,
    Beers,
    SpeechBalloon,
    CardFileBox,
    LoudSound,
    Mute,
    BustsInSilhouette,
    ChildrenCrossing,
    BuildingConstruction,
    Iphone,
    ClownFace,
    Egg,
    SeeNoEvil,
    CameraFlash,
    Alembic,
    Mag,
    Label,
    Seedling,
    TriangularFlagOnPost,
    GoalNet,
    Dizzy,
    Wastebasket,
    PassportControl,
    AdhesiveBandage,
    MonocleFace,
    Coffin,
    TestTube,
    Necktie,
    Stethoscope,
    Bricks,
    Technologist,
    MoneyWithWings,
    Thread,
    SafetyVest,
    // Define additional emojis as needed
}

impl GitHubEmoji {
    fn character(&self) -> char {
        match self {
            GitHubEmoji::Art => '🎨',
            GitHubEmoji::Zap => '⚡',
            GitHubEmoji::Fire => '🔥',
            GitHubEmoji::Bug => '🐛',
            GitHubEmoji::Ambulance => '🚑',
            GitHubEmoji::Sparkles => '✨',
            GitHubEmoji::Memo => '📝',
            GitHubEmoji::Rocket => '🚀',
            GitHubEmoji::Lipstick => '💄',
            GitHubEmoji::Tada => '🎉',
            GitHubEmoji::WhiteCheckMark => '✅',
            GitHubEmoji::Lock => '🔒',
            GitHubEmoji::ClosedLockWithKey => '🔐',
            GitHubEmoji::Bookmark => '🔖',
            GitHubEmoji::RotatingLight => '🚨',
            GitHubEmoji::Construction => '🚧',
            GitHubEmoji::GreenHeart => '💚',
            // GitHubEmoji::ArrowDown => '⬇️',
            // GitHubEmoji::ArrowUp => '⬆️',
            // GitHubEmoji::Pushpin => '📌',
            GitHubEmoji::ConstructionWorker => '👷',
            GitHubEmoji::ChartWithUpwardsTrend => '📈',
            // GitHubEmoji::Recycle => '♻️',
            GitHubEmoji::HeavyPlusSign => '➕',
            GitHubEmoji::HeavyMinusSign => '➖',
            GitHubEmoji::Wrench => '🔧',
            GitHubEmoji::Hammer => '🔨',
            GitHubEmoji::GlobeWithMeridians => '🌐',
            // GitHubEmoji::Pencil2 => '✏️',
            //     GitHubEmoji::Poop => '💩',
            GitHubEmoji::Rewind => '⏪',
            GitHubEmoji::TwistedRightwardsArrows => '🔀',
            GitHubEmoji::Package => '📦',
            GitHubEmoji::Alien => '👽',
            GitHubEmoji::Truck => '🚚',
            GitHubEmoji::PageFacingUp => '📄',
            GitHubEmoji::Boom => '💥',
            GitHubEmoji::Bento => '🍱',
            GitHubEmoji::Wheelchair => '♿',
            GitHubEmoji::Bulb => '💡',
            GitHubEmoji::Beers => '🍻',
            GitHubEmoji::SpeechBalloon => '💬',
            GitHubEmoji::CardFileBox => '🗃',
            GitHubEmoji::LoudSound => '🔊',
            GitHubEmoji::Mute => '🔇',
            GitHubEmoji::BustsInSilhouette => '👥',
            GitHubEmoji::ChildrenCrossing => '🚸',
            GitHubEmoji::BuildingConstruction => '🏗',
            GitHubEmoji::Iphone => '📱',
            GitHubEmoji::ClownFace => '🤡',
            GitHubEmoji::Egg => '🥚',
            GitHubEmoji::SeeNoEvil => '🙈',
            GitHubEmoji::CameraFlash => '📸',
            // GitHubEmoji::Alembic => '⚗️',
            //     GitHubEmoji::Mag => '🔍',
            // GitHubEmoji::Label => '🏷️',
            GitHubEmoji::Seedling => '🌱',
            GitHubEmoji::TriangularFlagOnPost => '🚩',
            GitHubEmoji::GoalNet => '🥅',
            GitHubEmoji::Dizzy => '💫',
            // GitHubEmoji::Wastebasket => '🗑️',
            //     GitHubEmoji::PassportControl => '🛂',
            GitHubEmoji::AdhesiveBandage => '🩹',
            GitHubEmoji::MonocleFace => '🧐',
            // GitHubEmoji::Coffin => '⚰️',
            GitHubEmoji::TestTube => '🧪',
            GitHubEmoji::Necktie => '👔',
            GitHubEmoji::Stethoscope => '🩺',
            GitHubEmoji::Bricks => '🧱',
            // GitHubEmoji::Technologist => '🧑‍💻',
            //     GitHubEmoji::MoneyWithWings => '💸',
            GitHubEmoji::Thread => '🧵',
            GitHubEmoji::SafetyVest => '🦺',
            // Continue for additional emojis
            _ => '❓',
        }
    }

    fn code(&self) -> &'static str {
        match self {
            GitHubEmoji::Art => ":art:",
            GitHubEmoji::Zap => ":zap:",
            GitHubEmoji::Fire => ":fire:",
            GitHubEmoji::Bug => ":bug:",
            GitHubEmoji::Ambulance => ":ambulance:",
            GitHubEmoji::Sparkles => ":sparkles:",
            GitHubEmoji::Memo => ":memo:",
            GitHubEmoji::Rocket => ":rocket:",
            GitHubEmoji::Lipstick => ":lipstick:",
            GitHubEmoji::Tada => ":tada:",
            GitHubEmoji::WhiteCheckMark => ":white_check_mark:",
            GitHubEmoji::Lock => ":lock:",
            GitHubEmoji::ClosedLockWithKey => ":closed_lock_with_key:",
            GitHubEmoji::Bookmark => ":bookmark:",
            GitHubEmoji::RotatingLight => ":rotating_light:",
            GitHubEmoji::Construction => ":construction:",
            GitHubEmoji::GreenHeart => ":green_heart:",
            GitHubEmoji::ArrowDown => ":arrow_down:",
            GitHubEmoji::ArrowUp => ":arrow_up:",
            GitHubEmoji::Pushpin => ":pushpin:",
            GitHubEmoji::ConstructionWorker => ":construction_worker:",
            GitHubEmoji::ChartWithUpwardsTrend => ":chart_with_upwards_trend:",
            GitHubEmoji::Recycle => ":recycle:",
            GitHubEmoji::HeavyPlusSign => ":heavy_plus_sign:",
            GitHubEmoji::HeavyMinusSign => ":heavy_minus_sign:",
            GitHubEmoji::Wrench => ":wrench:",
            GitHubEmoji::Hammer => ":hammer:",
            GitHubEmoji::GlobeWithMeridians => ":globe_with_meridians:",
            GitHubEmoji::Pencil2 => ":pencil2:",
            GitHubEmoji::Poop => ":poop:",
            GitHubEmoji::Rewind => ":rewind:",
            GitHubEmoji::TwistedRightwardsArrows => ":twisted_rightwards_arrows:",
            GitHubEmoji::Package => ":package:",
            GitHubEmoji::Alien => ":alien:",
            GitHubEmoji::Truck => ":truck:",
            GitHubEmoji::PageFacingUp => ":page_facing_up:",
            GitHubEmoji::Boom => ":boom:",
            GitHubEmoji::Bento => ":bento:",
            GitHubEmoji::Wheelchair => ":wheelchair:",
            GitHubEmoji::Bulb => ":bulb:",
            GitHubEmoji::Beers => ":beers:",
            GitHubEmoji::SpeechBalloon => ":speech_balloon:",
            GitHubEmoji::CardFileBox => ":card_file_box:",
            GitHubEmoji::LoudSound => ":loud_sound:",
            GitHubEmoji::Mute => ":mute:",
            GitHubEmoji::BustsInSilhouette => ":busts_in_silhouette:",
            GitHubEmoji::ChildrenCrossing => ":children_crossing:",
            GitHubEmoji::BuildingConstruction => ":building_construction:",
            GitHubEmoji::Iphone => ":iphone:",
            GitHubEmoji::ClownFace => ":clown_face:",
            GitHubEmoji::Egg => ":egg:",
            GitHubEmoji::SeeNoEvil => ":see_no_evil:",
            GitHubEmoji::CameraFlash => ":camera_flash:",
            GitHubEmoji::Alembic => ":alembic:",
            GitHubEmoji::Mag => ":mag:",
            GitHubEmoji::Label => ":label:",
            GitHubEmoji::Seedling => ":seedling:",
            GitHubEmoji::TriangularFlagOnPost => ":triangular_flag_on_post:",
            GitHubEmoji::GoalNet => ":goal_net:",
            GitHubEmoji::Dizzy => ":dizzy:",
            GitHubEmoji::Wastebasket => ":wastebasket:",
            GitHubEmoji::PassportControl => ":passport_control:",
            GitHubEmoji::AdhesiveBandage => ":adhesive_bandage:",
            GitHubEmoji::MonocleFace => ":monocle_face:",
            GitHubEmoji::Coffin => ":coffin:",
            GitHubEmoji::TestTube => ":test_tube:",
            GitHubEmoji::Necktie => ":necktie:",
            GitHubEmoji::Stethoscope => ":stethoscope:",
            GitHubEmoji::Bricks => ":bricks:",
            GitHubEmoji::Technologist => ":technologist:",
            GitHubEmoji::MoneyWithWings => ":money_with_wings:",
            GitHubEmoji::Thread => ":thread:",
            GitHubEmoji::SafetyVest => ":safety_vest:",
            // Continue for additional emojis
        }
    }
}
