#[derive(Debug, Clone, Copy)]
enum GitHubEmoji {
    InitialCommit,
    VersionTag,
    NewFeature,
    Bugfix,
    Metadata,
    Documentation,
    DocumentingSourceCode,
    Performance,
    Cosmetic,
    Tests,
    AddingATest,
    MakeATestPass,
    GeneralUpdate,
    ImproveFormatStructure,
    RefactorCode,
    RemovingCodeFiles,
    ContinuousIntegration,
    Security,
    UpgradingDependencies,
    DowngradingDependencies,
    Lint,
    Translation,
    Text,
    CriticalHotfix,
    DeployingStuff,
    FixingOnMacOS,
    FixingOnLinux,
    FixingOnWindows,
    WorkInProgress,
    AddingCIBuildSystem,
    AnalyticsOrTrackingCode,
    RemovingADependency,
    AddingADependency,
    Docker,
    ConfigurationFiles,
    PackageJsonInJS,
    MergingBranches,
    BadCodeNeedImprovement,
    RevertingChanges,
    BreakingChanges,
    CodeReviewChanges,
    Accessibility,
    MoveRenameRepository,
}

impl GitHubEmoji {
    fn character(&self) -> char {
        match self {
            GitHubEmoji::InitialCommit => '🎉',
            GitHubEmoji::VersionTag => '🔖',
            GitHubEmoji::NewFeature => '✨',
            GitHubEmoji::Bugfix => '🐛',
            GitHubEmoji::Metadata => '📇',
            GitHubEmoji::Documentation => '📚',
            GitHubEmoji::DocumentingSourceCode => '💡',
            GitHubEmoji::Performance => '🐎',
            GitHubEmoji::Cosmetic => '💄',
            GitHubEmoji::Tests => '🚨',
            GitHubEmoji::AddingATest => '✅',
            // GitHubEmoji::MakeATestPass => '✔️',
            // GitHubEmoji::GeneralUpdate => '⚡',
            GitHubEmoji::ImproveFormatStructure => '🎨',
            GitHubEmoji::RefactorCode => '🔨',
            GitHubEmoji::RemovingCodeFiles => '🔥',
            GitHubEmoji::ContinuousIntegration => '💚',
            GitHubEmoji::Security => '🔒',
            // GitHubEmoji::UpgradingDependencies => '⬆️',
            // GitHubEmoji::DowngradingDependencies => '⬇️',
            // GitHubEmoji::Lint => '👕',
            GitHubEmoji::Translation => '👽',
            GitHubEmoji::Text => '📝',
            GitHubEmoji::CriticalHotfix => '🚑',
            GitHubEmoji::DeployingStuff => '🚀',
            GitHubEmoji::FixingOnMacOS => '🍎',
            GitHubEmoji::FixingOnLinux => '🐧',
            GitHubEmoji::FixingOnWindows => '🏁',
            GitHubEmoji::WorkInProgress => '🚧',
            GitHubEmoji::AddingCIBuildSystem => '👷',
            GitHubEmoji::AnalyticsOrTrackingCode => '📈',
            GitHubEmoji::RemovingADependency => '➖',
            GitHubEmoji::AddingADependency => '➕',
            GitHubEmoji::Docker => '🐳',
            GitHubEmoji::ConfigurationFiles => '🔧',
            GitHubEmoji::PackageJsonInJS => '📦',
            GitHubEmoji::MergingBranches => '🔀',
            GitHubEmoji::BadCodeNeedImprovement => '💩',
            GitHubEmoji::RevertingChanges => '⏪',
            GitHubEmoji::BreakingChanges => '💥',
            GitHubEmoji::CodeReviewChanges => '👌',
            GitHubEmoji::Accessibility => '♿',
            GitHubEmoji::MoveRenameRepository => '🚚',
            _ => '❓',
        }
    }

    fn code(&self) -> &'static str {
        match self {
            GitHubEmoji::InitialCommit => ":tada:",
            GitHubEmoji::VersionTag => ":bookmark:",
            GitHubEmoji::NewFeature => ":sparkles:",
            GitHubEmoji::Bugfix => ":bug:",
            GitHubEmoji::Metadata => ":card_index:",
            GitHubEmoji::Documentation => ":books:",
            GitHubEmoji::DocumentingSourceCode => ":bulb:",
            GitHubEmoji::Performance => ":racehorse:",
            GitHubEmoji::Cosmetic => ":lipstick:",
            GitHubEmoji::Tests => ":rotating_light:",
            GitHubEmoji::AddingATest => ":white_check_mark:",
            GitHubEmoji::MakeATestPass => ":heavy_check_mark:",
            GitHubEmoji::GeneralUpdate => ":zap:",
            GitHubEmoji::ImproveFormatStructure => ":art:",
            GitHubEmoji::RefactorCode => ":hammer:",
            GitHubEmoji::RemovingCodeFiles => ":fire:",
            GitHubEmoji::ContinuousIntegration => ":green_heart:",
            GitHubEmoji::Security => ":lock:",
            GitHubEmoji::UpgradingDependencies => ":arrow_up:",
            GitHubEmoji::DowngradingDependencies => ":arrow_down:",
            GitHubEmoji::Lint => ":shirt:",
            GitHubEmoji::Translation => ":alien:",
            GitHubEmoji::Text => ":pencil:",
            GitHubEmoji::CriticalHotfix => ":ambulance:",
            GitHubEmoji::DeployingStuff => ":rocket:",
            GitHubEmoji::FixingOnMacOS => ":apple:",
            GitHubEmoji::FixingOnLinux => ":penguin:",
            GitHubEmoji::FixingOnWindows => ":checkered_flag:",
            GitHubEmoji::WorkInProgress => ":construction:",
            GitHubEmoji::AddingCIBuildSystem => ":construction_worker:",
            GitHubEmoji::AnalyticsOrTrackingCode => ":chart_with_upwards_trend:",
            GitHubEmoji::RemovingADependency => ":heavy_minus_sign:",
            GitHubEmoji::AddingADependency => ":heavy_plus_sign:",
            GitHubEmoji::Docker => ":whale:",
            GitHubEmoji::ConfigurationFiles => ":wrench:",
            GitHubEmoji::PackageJsonInJS => ":package:",
            GitHubEmoji::MergingBranches => ":twisted_rightwards_arrows:",
            GitHubEmoji::BadCodeNeedImprovement => ":hankey:",
            GitHubEmoji::RevertingChanges => ":rewind:",
            GitHubEmoji::BreakingChanges => ":boom:",
            GitHubEmoji::CodeReviewChanges => ":ok_hand:",
            GitHubEmoji::Accessibility => ":wheelchair:",
            GitHubEmoji::MoveRenameRepository => ":truck:",
        }
    }
}
