/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct CheckRunCheckSuite {
    #[serde(rename = "id")]
    pub id: i32,
}

impl CheckRunCheckSuite {
    pub fn new(id: i32) -> CheckRunCheckSuite {
        CheckRunCheckSuite { id }
    }

    pub fn builder() -> CheckRunCheckSuiteBuilder {
        CheckRunCheckSuiteBuilder::create_empty()
    }
}
