/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct FileCommitCommitParentsInner {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "html_url", skip_serializing_if = "Option::is_none")]
    pub html_url: Option<String>,
    #[serde(rename = "sha", skip_serializing_if = "Option::is_none")]
    pub sha: Option<String>,
}

impl FileCommitCommitParentsInner {
    pub fn new() -> FileCommitCommitParentsInner {
        FileCommitCommitParentsInner {
            url: None,
            html_url: None,
            sha: None,
        }
    }

    pub fn builder() -> FileCommitCommitParentsInnerBuilder {
        FileCommitCommitParentsInnerBuilder::create_empty()
    }
}
