/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct PullRequestMinimalHeadRepo {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl PullRequestMinimalHeadRepo {
    pub fn new(id: i64, url: String, name: String) -> PullRequestMinimalHeadRepo {
        PullRequestMinimalHeadRepo { id, url, name }
    }

    pub fn builder() -> PullRequestMinimalHeadRepoBuilder {
        PullRequestMinimalHeadRepoBuilder::create_empty()
    }
}
