/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct PullRequestMinimalHead {
    #[serde(rename = "ref")]
    pub r#ref: String,
    #[serde(rename = "sha")]
    pub sha: String,
    #[serde(rename = "repo")]
    pub repo: Box<models::PullRequestMinimalHeadRepo>,
}

impl PullRequestMinimalHead {
    pub fn new(
        r#ref: String, sha: String, repo: models::PullRequestMinimalHeadRepo,
    ) -> PullRequestMinimalHead {
        PullRequestMinimalHead {
            r#ref,
            sha,
            repo: Box::new(repo),
        }
    }

    pub fn builder() -> PullRequestMinimalHeadBuilder {
        PullRequestMinimalHeadBuilder::create_empty()
    }
}
