/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct PullRequestReviewCommentLinksSelf {
    #[serde(rename = "href")]
    pub href: String,
}

impl PullRequestReviewCommentLinksSelf {
    pub fn new(href: String) -> PullRequestReviewCommentLinksSelf {
        PullRequestReviewCommentLinksSelf { href }
    }

    pub fn builder() -> PullRequestReviewCommentLinksSelfBuilder {
        PullRequestReviewCommentLinksSelfBuilder::create_empty()
    }
}
