/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct PullsUpdateReviewCommentRequest {
    /// The text of the reply to the review comment.
    #[serde(rename = "body")]
    pub body: String,
}

impl PullsUpdateReviewCommentRequest {
    pub fn new(body: String) -> PullsUpdateReviewCommentRequest {
        PullsUpdateReviewCommentRequest { body }
    }

    pub fn builder() -> PullsUpdateReviewCommentRequestBuilder {
        PullsUpdateReviewCommentRequestBuilder::create_empty()
    }
}
