/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// ReposDeleteFileRequestCommitter : object containing information about the committer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct ReposDeleteFileRequestCommitter {
    /// The name of the author (or committer) of the commit
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The email of the author (or committer) of the commit
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
}

impl ReposDeleteFileRequestCommitter {
    /// object containing information about the committer.
    pub fn new() -> ReposDeleteFileRequestCommitter {
        ReposDeleteFileRequestCommitter {
            name: None,
            email: None,
        }
    }

    pub fn builder() -> ReposDeleteFileRequestCommitterBuilder {
        ReposDeleteFileRequestCommitterBuilder::create_empty()
    }
}
