/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct ReposGetCommit503Response {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "documentation_url", skip_serializing_if = "Option::is_none")]
    pub documentation_url: Option<String>,
}

impl ReposGetCommit503Response {
    pub fn new() -> ReposGetCommit503Response {
        ReposGetCommit503Response {
            code: None,
            message: None,
            documentation_url: None,
        }
    }

    pub fn builder() -> ReposGetCommit503ResponseBuilder {
        ReposGetCommit503ResponseBuilder::create_empty()
    }
}
