/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct SecurityAndAnalysis {
    #[serde(rename = "advanced_security", skip_serializing_if = "Option::is_none")]
    pub advanced_security: Option<Box<models::SecurityAndAnalysisAdvancedSecurity>>,
    #[serde(
        rename = "dependabot_security_updates",
        skip_serializing_if = "Option::is_none"
    )]
    pub dependabot_security_updates:
        Option<Box<models::SecurityAndAnalysisDependabotSecurityUpdates>>,
    #[serde(rename = "secret_scanning", skip_serializing_if = "Option::is_none")]
    pub secret_scanning: Option<Box<models::SecurityAndAnalysisAdvancedSecurity>>,
    #[serde(
        rename = "secret_scanning_push_protection",
        skip_serializing_if = "Option::is_none"
    )]
    pub secret_scanning_push_protection: Option<Box<models::SecurityAndAnalysisAdvancedSecurity>>,
    #[serde(
        rename = "secret_scanning_non_provider_patterns",
        skip_serializing_if = "Option::is_none"
    )]
    pub secret_scanning_non_provider_patterns:
        Option<Box<models::SecurityAndAnalysisAdvancedSecurity>>,
}

impl SecurityAndAnalysis {
    pub fn new() -> SecurityAndAnalysis {
        SecurityAndAnalysis {
            advanced_security: None,
            dependabot_security_updates: None,
            secret_scanning: None,
            secret_scanning_push_protection: None,
            secret_scanning_non_provider_patterns: None,
        }
    }

    pub fn builder() -> SecurityAndAnalysisBuilder {
        SecurityAndAnalysisBuilder::create_empty()
    }
}
