/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Eq)]
#[serde(untagged)]
pub enum UsersGetAuthenticated200Response {
    PrivateUser(Box<models::PrivateUser>),
    PublicUser(Box<models::PublicUser>),
}

impl Default for UsersGetAuthenticated200Response {
    fn default() -> Self {
        Self::PrivateUser(Default::default())
    }
}
