/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// ValidationErrorSimple : Validation Error Simple
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder, Eq)]
#[builder(setter(strip_option, into), default)]
pub struct ValidationErrorSimple {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "documentation_url")]
    pub documentation_url: String,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<String>>,
}

impl ValidationErrorSimple {
    /// Validation Error Simple
    pub fn new(message: String, documentation_url: String) -> ValidationErrorSimple {
        ValidationErrorSimple {
            message,
            documentation_url,
            errors: None,
        }
    }

    pub fn builder() -> ValidationErrorSimpleBuilder {
        ValidationErrorSimpleBuilder::create_empty()
    }
}
