derives:
  message:
    - target: "."
      derive: "derive_builder::Builder"
      condition: "use_builder"
    - target: "."
      derive: "utoipa::ToSchema"
    - target: "."
      derive: "serde::Serialize"
    - target: "."
      derive: "serde::Deserialize"
  enum: [ ]
  all:
    - target: "."
      derive: "utoipa::ToSchema"
    - target: "."
      derive: "serde::Serialize"
      condition: "documentation"
    - target: "."
      derive: "serde::Deserialize"
      condition: "documentation"
    - target: "Repository"
      derive: "utoipa::ToSchema"


attributes:
  message:
    - target: "CommitRangeAnalysis.repository"
      attribute: |
        #[schema(example = json!({"type": "github", "owner": "bazelbuild", "name": "rules_rust"}))]
      condition: "documentation"
    - target: "CommitRangeAnalysis.commit_range"
      attribute: |
        #[schema(example = json!({
          "start_commit": "6c2bd67",
          "end_commit": "6b10ce3",
          "total_commits": 6,
          "total_additions": 1163,
          "total_deletions": 59,
          "top_contributors": [
            {"username": "Daniel Wagner-Hall", "commits": 1144},
            {"username": "Milan Vukov", "commits": 60},
            {"username": "Marcel Hlopko", "commits": 18}
          ]
        }))]
      condition: "documentation"
    - target: "CommitRangeRequest.repository"
      attribute: |
        #[schema(example = json!({"type": "github", "owner": "bazelbuild", "name": "rules_rust"}))]
      condition: "documentation"
    - target: "CommitRangeRequest.start_commit"
      attribute: |
        #[schema(example = "6c2bd67")]
      condition: "documentation"
    - target: "CommitRangeRequest.end_commit"
      attribute: |
        #[schema(example = "6b10ce3")]
      condition: "documentation"
    - target: "CommitRangeDetails.start_commit"
      attribute: |
        #[schema(example = "6c2bd67")]
      condition: "documentation"
    - target: "CommitRangeDetails.end_commit"
      attribute: |
        #[schema(example = "6b10ce3")]
      condition: "documentation"
    - target: "CommitRangeDetails.total_commits"
      attribute: |
        #[schema(example = "6")]
      condition: "documentation"
    - target: "CommitRangeDetails.total_additions"
      attribute: |
        #[schema(example = "1163")]
      condition: "documentation"
    - target: "CommitRangeDetails.total_deletions"
      attribute: |
        #[schema(example = "59")]
      condition: "documentation"
    - target: "CommitRangeDetails.top_contributors"
      attribute: |
        #[schema(example = json!([
          {"username": "Daniel Wagner-Hall", "commits": 1144},
          {"username": "Milan Vukov", "commits": 60},
          {"username": "Marcel Hlopko", "commits": 18}
        ]))]
    #    - target: "Repository"
    #      attribute: |
    #        #[serde::serde(tag = "type")]
    - target: "repository_details.Specifics.GitHubRepository"
      attribute: |
        #[schema(
        title = "GitHubRepository",
        example = json!({
            "type": "github",
            "owner": "bazelbuild",
            "name": "rules_rust",
            "connection": {
            "protocol": "https",
            "token": "example-token"
            }
        })
        )]
    - target: "repository_details.Specifics.GitHubRepository"
      attribute: |
        #[schema(
        title = "GitLabRepository",
        example = json!({
            "type": "gitlab",
            "owner": "gitlab-org",
            "name": "gitlab",
            "connection": {
            "protocol": "https",
            "token": "example-token"
            }
        })
        )]
    - target: "repository_details.Specifics.GitHubRepository"
      attribute: |
        #[schema(
        title = "BitbucketRepository",
        example = json!({
            "type": "bitbucket",
            "owner": "atlassian",
            "name": "pyramid",
            "connection": {
            "protocol": "https",
            "token": "example-token"
            }
        })
        )]
    - target: "repository_details.Specifics.AzureReposRepository"
      attribute: |
        #[schema(
        title = "AzureReposRepository",
        example = json!({
            "type": "azure_repos",
            "organization": "Microsoft",
            "project": "vscode",
            "repository": "vscode",
            "connection": {
            "protocol": "https",
            "token": "example-token"
            }
        })
        )]
    - target: "repository_details.Specifics.CustomRepository"
      attribute: |
        #[schema(
        title = "CustomRepository",
        example = json!({
            "type": "custom",
            "url": "https://custom.repo/url",
            "connection": {
            "protocol": "https",
            "token": "example-token"
            }
        })
        )]
  enum: [ ]
  all: [ ]

features:
  server:
    build_server: true
  client:
    build_client: true
  transport:
    build_transport: true


