# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opendrift.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fopendrift.proto\x12\topendrift\"\x8f\x01\n\x11SimulationRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12\x0b\n\x03lat\x18\x03 \x01(\x02\x12\x0e\n\x06radius\x18\x04 \x01(\x02\x12\x12\n\nstart_time\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x06 \x01(\t\x12\x16\n\x0e\x64uration_hours\x18\x07 \x01(\x05\"9\n\x12SimulationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bresult_file\x18\x02 \x01(\t2b\n\x12OpenDriftSimulator\x12L\n\rRunSimulation\x12\x1c.opendrift.SimulationRequest\x1a\x1d.opendrift.SimulationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opendrift_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMULATIONREQUEST']._serialized_start=31
  _globals['_SIMULATIONREQUEST']._serialized_end=174
  _globals['_SIMULATIONRESPONSE']._serialized_start=176
  _globals['_SIMULATIONRESPONSE']._serialized_end=233
  _globals['_OPENDRIFTSIMULATOR']._serialized_start=235
  _globals['_OPENDRIFTSIMULATOR']._serialized_end=333
# @@protoc_insertion_point(module_scope)
