[package]
name = "db-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
deluxe = "0.5.0"
darling = "0.20.10"
proc-macro2 = "1.0.86"
quote2 = "0.7.0"
syn = "2.0.72"
quote = "1.0.36"