/*
 * GitHub v3 REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Builder)]
#[builder(setter(strip_option, into), default)]
pub struct Verification {
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "payload", deserialize_with = "Option::deserialize")]
    pub payload: Option<String>,
    #[serde(rename = "signature", deserialize_with = "Option::deserialize")]
    pub signature: Option<String>,
}

impl Verification {
    pub fn new(
        verified: bool, reason: String, payload: Option<String>, signature: Option<String>,
    ) -> Verification {
        Verification {
            verified,
            reason,
            payload,
            signature,
        }
    }

    pub fn builder() -> VerificationBuilder {
        VerificationBuilder::create_empty()
    }
}

mod _impl_github {
    use external_github;

    use super::*;

    impl From<external_github::models::Verification> for Verification {
        fn from(internal: external_github::models::Verification) -> Self {
            Self {
                verified: internal.verified,
                reason: internal.reason,
                payload: internal.payload,
                signature: internal.signature,
            }
        }
    }

    impl From<Verification> for external_github::models::Verification {
        fn from(internal: Verification) -> Self {
            Self {
                verified: internal.verified,
                reason: internal.reason,
                payload: internal.payload,
                signature: internal.signature,
            }
        }
    }
}
