name: 'Rust CLI Test for Annotations'
description: 'Run Rust tests for the annotation functionality of the CLI application'
inputs:
  rust-version:
    description: 'The Rust version to use'
    required: true
    default: 'stable'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check Rust version
      run: rustup run ${{ inputs.rust-version }} rustc --version
      shell: bash
    - name: Run Annotation Test
      run: rustup run ${{ inputs.rust-version }} cargo run --bin test_annotation
      shell: bash
