[env]
CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY = "."
JAVA_OPTS = "-Dlog.level=off -Dorg.openapitools.codegen.languages.AbstractRustCodegen=off"
API_GENERATOR_COMMAND = "openapi-generator generate -g rust --template-dir core/templates/rust-templates"
COMMON_PROPERTIES = "useSingleRequestParameter=true,deriveBuilder=true,enableCache=true,tracing=true"
API_SPEC_PATH = "openapi"
OUTPUT_PATH = "generated"

[tasks.download-and-extract-spec]
description = "Download and extract API specification"
script_runner = "sh"
env = { JAVA_OPTS = "${JAVA_OPTS}" }
script = [
    "echo Downloading and extracting OpenAPI spec for $API_NAME",
    "curl -L -o ${API_SPEC_PATH}/${API_NAME}_spec.${API_EXT} ${API_URL}",
    "if [ \"$API_EXT\" = \"yaml\" ]; then",
    "  command -v yaml2json >/dev/null 2>&1 || { echo >&2 'yaml2json is not installed. Installing...'; npm install -g yaml2json; }",
    "  yaml2json ${API_SPEC_PATH}/${API_NAME}_spec.yaml > ${API_SPEC_PATH}/${API_NAME}_spec.json",
    "elif [ \"$API_EXT\" = \"zip\" ]; then",
    "  unzip -o ${API_SPEC_PATH}/${API_NAME}_spec.zip -d ${API_SPEC_PATH}/${API_NAME}_spec",
    "  node ${API_SPEC_PATH}/extract_${API_NAME}.js ${API_SPEC_PATH}/${API_NAME}_spec",
    "else",
    "  node ${API_SPEC_PATH}/extract_${API_NAME}.js",
    "fi"
]

[tasks.generate-client]
description = "Generate API client"
dependencies = ["download-and-extract-spec"]
script_runner = "sh"
env = { JAVA_OPTS = "${JAVA_OPTS}", API_GENERATOR_COMMAND = "${API_GENERATOR_COMMAND}", COMMON_PROPERTIES = "${COMMON_PROPERTIES}" }
script = [
    "echo Generating client for $API_NAME",
    "${API_GENERATOR_COMMAND} -i ${API_SPEC_PATH}/${API_NAME}_spec.json -o ${OUTPUT_PATH}/external_${API_NAME} --additional-properties=packageName=external_${API_NAME},${COMMON_PROPERTIES} 2>&1 | grep -v 'WARN' | grep -v 'INFO'",
    "echo Formatting code for $API_NAME",
    "cargo fmt --manifest-path ${OUTPUT_PATH}/external_${API_NAME}/Cargo.toml"
]

# Specific tasks for APIs
[tasks.generate-openai-client]
run_task = "download-and-extract-spec"
env = { API_NAME = "openai", API_URL = "https://raw.githubusercontent.com/openai/openai-openapi/cd3c3feb77931b5fd1e8b9c1eb5fb1697821a0d0/openapi.yaml", API_EXT = "yaml" }

[tasks.generate-github-client]
run_task = "download-and-extract-spec"
env = { API_NAME = "github", API_URL = "https://github.com/github/rest-api-description/raw/main/descriptions/api.github.com/api.github.com.2022-11-28.json", API_EXT = "json" }

[tasks.generate-azure-client]
run_task = "download-and-extract-spec"
env = { API_NAME = "azure", API_URL = "https://github.com/MicrosoftDocs/vsts-rest-api-specs/archive/refs/heads/master.zip", API_EXT = "zip" }

[tasks.generate-clients]
description = "Generate and format GitHub, Azure, and OpenAI clients"
dependencies = ["generate-github-client", "generate-azure-client", "generate-openai-client"]
