name: Generate Clients 🛠️

on:
  push:
    branches:
      - master

jobs:
  generate_code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client:
          - { type: 'python', extra_args: '--additional-properties=packageName=devpulse_client' }
          - { type: 'rust', extra_args: '' }
          - { type: 'csharp', extra_args: '' }
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code
        uses: hatamiarash7/openapi-generator@v0.3.0
        with:
          generator: ${{ matrix.client.type }}
          #openapi-file: ${{ secrets.OPENAPI_SPEC_PATH }}
          openapi-url: https://devpulse.shuttleapp.rs/api-docs/openapi.json
          #          openapi-url: https://devpulse.shuttleapp.rs/api/v1/openapi.json <-- soon
          output-dir: ${{ matrix.client.type }}-client
          command-args: ${{ matrix.client.extra_args }}

      - name: Upload generated code
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.client.type }}-client
          path: ${{ matrix.client.type }}-client

