name: Rust

on:
  push:
    branches: [
      "master",
      "develop",
      "feature/*"
    ]
  pull_request:
    branches: [
      "master",
      "develop",
      "feature/*"
    ]

env:
  CARGO_TERM_COLOR: always
  CACHE_NUMBER: 0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Step to cache Cargo dependencies
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo 
            ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ env.CACHE_NUMBER }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Step to install protobuf compiler
      - name: Install protobuf compiler
        run: sudo apt-get install protobuf-compiler

      # Build step
      - name: Build
        run: cargo build --verbose

      # Test step
      - name: Run tests
        run: cargo test --verbose
