name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 0: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Cache Cargo dependencies
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo 
            ~/.rustup
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Step 2: Run annotation test
      - name: Run annotation test
        run: cargo run --bin annotate
        continue-on-error: true

#      # Step 3: Check for annotations
#      - name: Check for annotations
#        run: python check_annotations.py
#        working-directory: ./tests
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GITHUB_REPOSITORY: ${{ github.repository }}
#          GITHUB_RUN_ID: ${{ github.run_id }}